
services:
  postgres:
    container_name: database_prisma_node
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpass@123
      - POSTGRES_DB=ignite_prisma
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
    